'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contact
    Public Property ID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property CreditCardNumber As String
    Public Property Email As String
    Public Property Phone As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Photo As Byte()

End Class
