Imports Microsoft.VisualBasic
Imports DevExpress.Mvvm
Imports DevExpress.Mvvm.DataAnnotations
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema
Imports DataAnnotationAttributes.Model
'Imports DataAnnotationAttributes.Contact

    '<MetadataType(GetType(ContactMetadata))> _
Partial Public Class Contact
    Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Contact))
        builder.Group("General Info").ContainsProperty(Function(x) x.FirstName).ContainsProperty(Function(x) x.LastName).ContainsProperty(Function(x) x.CreditCardNumber).EndGroup().Group("Contacts").ContainsProperty(Function(x) x.Email).ContainsProperty(Function(x) x.Phone).EndGroup().Group("Address").ContainsProperty(Function(x) x.Address).ContainsProperty(Function(x) x.City).ContainsProperty(Function(x) x.State).ContainsProperty(Function(x) x.Zip).EndGroup()

        builder.Property(Function(x) x.ID).NotAutoGenerated()

        builder.Property(Function(x) x.FirstName).Required()
        builder.Property(Function(x) x.FirstName).MaxLength(25, Function() "Value is too long")

        builder.Property(Function(x) x.LastName).Required()

        builder.Property(Function(x) x.CreditCardNumber).CreditCardDataType()
        builder.Property(Function(x) x.CreditCardNumber).NullDisplayText("<empty>")

        builder.Property(Function(x) x.Email).EmailAddressDataType()
        builder.Property(Function(x) x.Email).NullDisplayText("<empty>")

        builder.Property(Function(x) x.Phone).PhoneNumberDataType()
        builder.Property(Function(x) x.Phone).NullDisplayText("<empty>")

        builder.Property(Function(x) x.Address).NullDisplayText("<empty>")

        builder.Property(Function(x) x.City).NullDisplayText("<empty>")
        builder.Property(Function(x) x.City).RegExMask("\w{1,25}")

        builder.Property(Function(x) x.State).NullDisplayText("<empty>")

        builder.Property(Function(x) x.Zip).NullDisplayText("<empty>")

        builder.Property(Function(x) x.Photo).NotAutoGenerated()
        builder.Property(Function(x) x.Photo).NullDisplayText("<empty>")
    End Sub
    'Public Class ContactMetadata
    '    Implements IMetadataProvider(Of Contact)

    'End Class
End Class
